services:
  toasty-postgres:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  toasty-qdrant:
    image: qdrant/qdrant:v1.14.1
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/collections" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    volumes:
      - qdrant_db:/qdrant/storage

  toasty-redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  toasty-celery-worker:
    build: .
    command: celery -A toasty worker -l info
    depends_on:
      toasty-redis:
        condition: service_started
      toasty-postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    restart: on-failure
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@toasty-postgres:5432/${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  toasty-app:
    build: .
    depends_on:
      toasty-postgres:
        condition: service_healthy
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT}:8000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@toasty-postgres:5432/${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: ./entrypoint.sh

  toasty-init:
    profiles:
      - init
    build: .
    depends_on:
      toasty-postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@toasty-postgres:5432/${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: ./entrypoint.sh

volumes:
  postgres_db:
  qdrant_db:
